package com.example.appcash.navigation

object Destinations {
    const val MAIN_NOTES_FOLDER_SCREEN = "MAIN_NOTES_FOLDER_SCREEN"

    const val NOTES_LIST_SCREEN = "NOTES_LIST_SCREEN"

    const val NOTE_SCREEN = "NOTE_SCREEN"

    const val MAIN_TASKS_FOLDER_SCREEN = "MAIN_TASKS_SCREEN"

    const val TASKS_SCREEN = "TASKS_SCREEN"

    const val MAIN_CALENDAR_SCREEN = "MAIN_CALENDAR_SCREEN"

    const val MAIN_FINANCE_SCREEN = "MAIN_FINANCE_SCREEN"

    const val CREATING_FINANCE_FOLDER_SCREEN = "CREATING_FINANCE_FOLDER_SCREEN"

    const val FINANCE_ACCOUNTING_SCREEN = "FINANCE_ACCOUNTING_SCREEN"

    const val ERROR_SCREEN = "ERROR_SCREEN"
}